/** Auto-generated by scripts/sync-mystic-seo-report.mjs — do not edit by hand. */

export const mysticSeoReport = {
  "clientName": "Mystic Caribbean Resto & Bar",
  "domain": "mysticrestobar.com",
  "location": "Brampton, ON",
  "reportDate": "2026-06-28",
  "baseline": {
    "total": 32,
    "label": "SpotHopper template",
    "date": "2026-04-08",
    "issues": [
      "No Restaurant schema",
      "15 H1 tags on homepage",
      "989-char meta description",
      "No native ordering",
      "Blank specials / stale events"
    ]
  },
  "current": {
    "total": 73,
    "technical": 50,
    "visibility": 23,
    "inTop10": 15,
    "keywordCount": 32,
    "technicalChecks": [
      "robots + sitemap",
      "sitemap-index",
      "Restaurant schema",
      "EventVenue schema",
      "FAQ schema",
      "Toast ordering"
    ]
  },
  "dashboardUrl": "https://dashboard.forge-co.ca/client/mystic-caribbean",
  "keywords": [
    {
      "keyword": "restaurant Brampton Kennedy Road",
      "category": "local",
      "rank": 1,
      "previousRank": 1,
      "change": 0
    },
    {
      "keyword": "Mystic Caribbean Brampton",
      "category": "brand",
      "rank": 1,
      "previousRank": 1,
      "change": 0
    },
    {
      "keyword": "Caribbean bar Brampton",
      "category": "bar",
      "rank": 1,
      "previousRank": null,
      "change": null
    },
    {
      "keyword": "dance floor restaurant Brampton",
      "category": "events",
      "rank": 1,
      "previousRank": null,
      "change": null
    },
    {
      "keyword": "Chinese Caribbean restaurant Brampton",
      "category": "core",
      "rank": 2,
      "previousRank": 2,
      "change": 0
    },
    {
      "keyword": "Caribbean restaurant Brampton",
      "category": "core",
      "rank": 2,
      "previousRank": 3,
      "change": 1
    },
    {
      "keyword": "Chinese Caribbean fusion Brampton",
      "category": "core",
      "rank": 2,
      "previousRank": 2,
      "change": 0
    },
    {
      "keyword": "fusion restaurant Brampton",
      "category": "core",
      "rank": 2,
      "previousRank": 2,
      "change": 0
    },
    {
      "keyword": "Chinese Caribbean food near me",
      "category": "core",
      "rank": 2,
      "previousRank": null,
      "change": null
    },
    {
      "keyword": "cocktail bar Brampton",
      "category": "bar",
      "rank": 3,
      "previousRank": null,
      "change": null
    },
    {
      "keyword": "Trinidad restaurant Brampton",
      "category": "core",
      "rank": 3,
      "previousRank": null,
      "change": null
    },
    {
      "keyword": "Trinidadian food Brampton",
      "category": "menu",
      "rank": 5,
      "previousRank": 5,
      "change": 0
    },
    {
      "keyword": "live music restaurant Brampton",
      "category": "events",
      "rank": 6,
      "previousRank": 9,
      "change": 3
    },
    {
      "keyword": "lo mein Brampton",
      "category": "menu",
      "rank": 8,
      "previousRank": null,
      "change": null
    },
    {
      "keyword": "rehearsal dinner Brampton",
      "category": "events",
      "rank": 9,
      "previousRank": null,
      "change": null
    },
    {
      "keyword": "bar and restaurant Brampton",
      "category": "bar",
      "rank": 13,
      "previousRank": null,
      "change": null
    },
    {
      "keyword": "birthday party restaurant Brampton",
      "category": "events",
      "rank": 17,
      "previousRank": null,
      "change": null
    }
  ]
} as const;

export type MysticSeoReport = typeof mysticSeoReport;
